live_config_reload = true

import = [
   #"~/.config/alacritty/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity =0.95

[window.dimensions]
columns = 200
lines = 40

[window.padding]
x = 10
y = 10

[font]
size = 15

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"
